### PR TITLE
Added standard email signup features

### PR DESCRIPTION
**Pull request by glidester**
This silhouette example was just what I was looking for apart from missing the email signup features of secure social. 

I've added the same email signup features as present in the old play-multidomain-auth project.

Let me know if there are any issues.

Cheers & thanks for all your hard work!

### CODE REVIEW

**Comment by akkie** [comment]
@glidester I really appreciate your work on this, but I cannot merge the pull request because I've this functionality already implemented locally. I will release this with the next Play version in November.

Anyway I'll let this pull request open so that the other users can use your fork for the current version of Silhouette. I'll also add your fork to the documentation.

Sorry!

**Comment by glidester** [comment]
No worries @akkie, good to know this functionality is coming down the pipe soon. :)

**Comment by AlexJoom** [comment]
@akkie are you going to publish your code any time soon? 
In any case thanks for making the code public and also to @glidester for the contribution! Saved me some time:)

**Comment by akkie** [comment]
I'll release it if Silhouette 4 is in the release phase. The plan is to release a first release candidate at the end of November.

**Comment by kkirancse** [comment]
@akkie, Is it released?

**Comment by akkie** [comment]
No. It comes with the next Play 2.5 release next year. Maybe end of January or eventually in February. I'll port the templates at the beginning of the next year.

**Comment by akkie** [comment]
Fixed with #83

**Pull request closed without merging**
