### PR TITLE
Added password strength meter

### PR DESCRIPTION
**Pull request by mslinn**
The stylesheet needs to be tweaked so the HTML5 meter element displays the password strength as a color bar. Works fine in Firefox. Did not test with any other browsers, more stylesheet tweaks might be required for Safari, IE, etc.

### CODE REVIEW

**Comment by akkie** [comment]
:+1:

**Comment by akkie** [comment]
The style for a page gets completely changed if the password strength field is displayed. It seems that it overrides the global style.

https://play-silhouette-seed.herokuapp.com/signIn (Default style)
https://play-silhouette-seed.herokuapp.com/signUp (New Style)

Anyway, I like the new style. Maybe we can use it for any page?

**Comment by mslinn** [comment]
I did not notice that. Easy enough to make the change, just consolidate the new /assets/styles/zxcvbnShim.css into /assets/styles/main.css. That is probably a good idea anyway.

**Comment by akkie** [comment]
It would be awesome if you could help me here by providing a pull request. I currently write the missing documentation for the persistence layer and the cryptographic components.

**Comment by mslinn** [comment]
OK

**Pull request merged**
