### PR TITLE
Added CAS

### PR DESCRIPTION
**Pull request by arjunsol**
Added support for the CAS provider.

### CODE REVIEW

**Comment by SBSMMO** [comment]
Hi,

Would it be possible for you to create a beta branch for the 4.0 version of the seed? Then I can look at enabling a CAS demo.

Thanks

**Comment by akkie** [comment]
I've released a BETA2 version.

**Comment by akkie** [comment]
Sorry I've completely misunderstand your question. I've published a BETA2 of Silhouette with your CAS changes and not a 4.0 version of the seed.

Please give me a week with the updated seed template.

**Comment by SBSMMO** [comment]
OK, thanks.

**Comment by SBSMMO** [comment]
Resubmitted here: https://github.com/mohiva/play-silhouette-seed/pull/74

**Pull request closed without merging**
