### PR TITLE
Add an activator tutorial

### PR DESCRIPTION
**Pull request by agoetschm**
Hi !

This PR is here because I thought it was more appropriate to have this discussion here than asking a question on the forum. So I hope I was right, I'm new to the this !

First I want to thank you @akkie for all your work with Silhouette ! But as I noticed, I am not the first one to wish for more documentation/tutorials (https://github.com/mohiva/play-silhouette/issues/385). As I see it, the [doc](https://www.silhouette.rocks/) and the seeds make it now fairly easy for a programmer experienced with Play and authentication to learn how to use Silhouette in a few hours. But for more "amateur" programmers like me, I think it would be really nice to have some sort of step-by-step tutorial linking all the concepts explained in the doc to an explicit and working example. This seed is very good, but I got a little bit lost at the beginning, and I imagine it can discourage some people.

So I thought I could try to contribute by adding an activator tutorial to this seed. What do you think ? Did I miss something and a tutorial like that already exists ? Or is someone already working on it ? I just want to be sure before actually writing the tutorial.

Best regards,
Anselme

### CODE REVIEW

**Comment by akkie** [comment]
@agoetschm That would be really great :+1:

**Comment by agoetschm** [comment]
I tried to squash the commits, but now it looks like I did the works two weeks ago.
I'm not used to write in English, so feel free to change anything.

**Comment by akkie** [comment]
@agoetschm Seems good at the first glance :+1: Let me checkout the code locally to see how it looks in activator.

Regarding the squashing. This isn't necessary anymore, because GitHub has now the option to squash the commits.

**Comment by akkie** [comment]
@agoetschm Thanks, it looks really great!

Could you please change the URLs from `http://www.silhouette.rocks` to `https://www.silhouette.rocks`.
And could you please indent the file with 4 spaces instead of tabs? We indent always with spaces in this project. And GitHub cannot really display tabs, because it uses always 8 spaces.

**Comment by akkie** [comment]
@agoetschm Thanks :+1:

**Pull request merged**
